"""followers

Revision ID: 800570a9def7
Revises: 9a1e4b254d8b
Create Date: 2022-03-29 11:41:46.291632

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '800570a9def7'
down_revision = '9a1e4b254d8b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('followers',
    sa.Column('follower_id', sa.Integer(), nullable=True),
    sa.Column('followed_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['followed_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['follower_id'], ['user.id'], )
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('followers')
    # ### end Alembic commands ###
